In [1]:
import warnings
import numpy as np
import pandas as pd
import os
warnings.simplefilter("ignore", np.RankWarning)

if not os.path.exists("ta_package"):
    os.system('git clone https://github.com/yuval-haim/HugoBot_2.0.git ')

In [2]:
data = pd.read_csv("FAGender.csv")
output_dir = "./output_test_hugobot/"

### Low‑Level API Examples

In [3]:
from ta_package.methods.sax import sax

# Apply SAX discretization with 3 bins.
symbolic_series, states = sax(data, bins=3, per_variable=True)

print("SAX symbolic series:")
display(symbolic_series.head())
print("SAX states:")
print(states)

SAX symbolic series:

   EntityID  TemporalPropertyID  TimeStamp  TemporalPropertyValue  state
0         5                  44          6                    1.0      1
1         5                  44          7                    1.0      1
2         5                  44          8                    1.0      1
3         5                  44          9                    1.1      2
4         5                  44         10                    1.1      2

SAX states:
{-1: [-0.43072729929545756, 0.43072729929545744], 1: [-0.43072729929545756, 0.43072729929545744], 2: [-0.43072729929545756, 0.43072729929545744], 3: [-0.43072729929545756, 0.43072729929545744], 4: [-0.43072729929545756, 0.43072729929545744], 5: [-0.43072729929545756, 0.43072729929545744], 6: [-0.43072729929545756, 0.43072729929545744], 39: [-0.43072729929545756, 0.43072729929545744], 40: [-0.43072729929545756, 0.43072729929545744], 41: [-0.43072729929545756, 0.43072729929545744], 42: [-0.43072729929545756, 0.43072729929545744], 43: [-0.43072729929545756, 0.43072729929545744], 44: [-0.43072729929545756, 0.43072729929545744], 55: [-0.43072729929545756, 0.43072729929545744]}

In [4]:
from ta_package.methods.equal_width import equal_width

# Apply Equal Width discretization with 3 bins.
symbolic_series, states = equal_width(data, bins=5, per_variable=True)

print("Equal Width symbolic series:")
display(symbolic_series.head())
print("Equal Width states:")
print(states)

Equal Width symbolic series:

   EntityID  TemporalPropertyID  TimeStamp  TemporalPropertyValue  state
0         5                  44          6                    1.0      1
1         5                  44          7                    1.0      1
2         5                  44          8                    1.0      1
3         5                  44          9                    1.1      2
4         5                  44         10                    1.1      2

Equal Width states:
{-1: [0.2, 0.4, 0.6, 0.8], 1: [27.060000000000002, 41.22, 55.379999999999995, 69.54], 2: [12.82, 14.64, 16.46, 18.28], 3: [14.8, 18.6, 22.4, 26.2], 4: [14.8, 18.6, 22.4, 26.2], 5: [12.82, 14.64, 16.46, 18.28], 6: [30.0, 45.0, 60.0, 75.0], 39: [6.98, 8.26, 9.54, 10.82], 40: [88.2, 104.4, 120.6, 136.8], 41: [164.0, 183.0, 202.0, 221.0], 42: [122.0, 169.0, 216.0, 263.0], 43: [3.9400000000000004, 4.180000000000001, 4.42, 4.66], 44: [1.056, 1.242, 1.428, 1.6139999999999999], 55: [0.2, 0.4, 0.6, 0.8]}

In [5]:
from ta_package.methods.gradient import gradient

# Apply Gradient discretization with a gradient window size of 3 and 3 bins.
symbolic_series, states = gradient(data, gradient_window_size=14, bins=3, close_to_zero_percentage = 30, per_variable=True) # 

print("Gradient symbolic series:")
display(symbolic_series.head())
print("Gradient states:")
print(states)

Gradient symbolic series:

,EntityID,TemporalPropertyID,TimeStamp,TemporalPropertyValue,angle,state
1106,5,2,9,20.1,NaN,-1
1107,5,2,12,20.1,-2.714073e-14,1
1108,5,2,17,20.1,-4.489224e-14,1
1109,5,2,24,20.1,-6.408218e-15,2
1110,5,2,31,20.1,-9.527138e-15,2

Gradient states:
{1: [1.6450514543386675e-14, 48.918885329437906], 2: [-1.1650242136581006e-14, 2.100084055241401e-14], 3: [-1.5877839247743975e-14, 2.661681744946431e-14], 4: [-6.408217703523115e-15, 4.707018550527229e-14], 5: [-6.408217703523115e-15, 1.5253949376414637e-14], 6: [42.21759379995638, 60.25323486738442], 39: [-4.594205195562309, -0.0798042623302442], 40: [-6.409298087412797e-14, 7.97069862874838e-15], 41: [-5.036744586559252e-13, 7.988621074358014e-14], 42: [-59.89869543440032, -3.1352324179412754e-14], 43: [-0.3376317184734337, 0.7366194348659766], 44: [-8.322355836892118e-15, 0.40730474172839437], 55: [-45, 45]}

In [6]:
from ta_package.methods.td4c import td4c

# Apply TD4C using 3 bins, working per variable, with a chosen distance measure.
symbolic_series, states = td4c(data, bins=3, distance_measure="kullback_leibler")

print("TD4C symbolic series:")
display(symbolic_series.head())
print("TD4C states:")
print(states)

TD4C symbolic series:

   EntityID  TemporalPropertyID  TimeStamp  TemporalPropertyValue  state
0         5                  44          6                    1.0      3
1         5                  44          7                    1.0      3
2         5                  44          8                    1.0      3
3         5                  44          9                    1.1      3
4         5                  44         10                    1.1      3

TD4C states:
{1: [15.0, 25.0], 2: [20.1], 3: [20.1, 30.0], 4: [20.0, 20.1], 5: [20.1], 6: [28.0, 30.0], 39: [6.3, 6.5], 40: [74.0, 86.0], 41: [150.0, 154.0], 42: [95.0, 119.0], 43: [3.9, 4.1], 44: [0.9, 0.91], 55: [1.0]}

### (b) High‑Level API Example (Single‑Method Mode)

In [7]:
from ta_package import TemporalAbstraction

ta = TemporalAbstraction(data)

# Use the high-level API to apply SAX (single-method mode).
final_result, final_states = ta.apply(method="sax", bins=3, per_variable=True, 
                                      paa="mean", paa_window=5,
                                      split_test=False, 
                                      save_output=True, output_dir= os.path.join(output_dir, "sax"), 
                                      max_gap=1)

print("High-level SAX result:")
display(final_result.head())
print("High-level SAX states:")
print(final_states)

Results saved in directory: ./output_test_hugobot/sax
High-level SAX result:

   EntityID  TemporalPropertyID  TimeStamp  TemporalPropertyValue  state
0         5                   2        2.0                   20.1      3
1         5                   2        7.0                   20.1      3
0         5                   3        2.0                   20.1      1
1         5                   3        7.0                   20.1      1
0         5                   4        2.0                   20.1      2

High-level SAX states:
{1: [-0.43072729929545756, 0.43072729929545744], 2: [-0.43072729929545756, 0.43072729929545744], 3: [-0.43072729929545756, 0.43072729929545744], 4: [-0.43072729929545756, 0.43072729929545744], 5: [-0.43072729929545756, 0.43072729929545744], 6: [-0.43072729929545756, 0.43072729929545744], 39: [-0.43072729929545756, 0.43072729929545744], 40: [-0.43072729929545756, 0.43072729929545744], 41: [-0.43072729929545756, 0.43072729929545744], 42: [-0.43072729929545756, 0.43072729929545744], 43: [-0.43072729929545756, 0.43072729929545744], 44: [-0.43072729929545756, 0.43072729929545744], 55: [-0.43072729929545756, 0.43072729929545744]}

### Example of Different Methods for Different Variables (Composite Mode)

In [8]:
# Composite configuration: for variable 1 use SAX, for variable 2 use Gradient.
method_config = {
    1: {"method": "sax", "bins": 3},
    2: {"method": "gradient", "bins": 3, "gradient_window_size": 14, "close_to_zero_percentage": 10},  # Fixed window size
    "default": {"method": "equal_frequency", "bins": 3}
}

ta = TemporalAbstraction(data)
final_result, final_states = ta.apply(method_config=method_config,
                                      split_test=False,
                                      save_output=True,
                                      output_dir=os.path.join(output_dir, "output_composite"),
                                      max_gap=1)


print("Composite mode symbolic series:")
display(final_result.head())
print("Composite mode states:")
print(final_states)

Results saved in directory: ./output_test_hugobot/output_composite
Composite mode symbolic series:

,EntityID,TemporalPropertyID,TimeStamp,TemporalPropertyValue,StateID,MethodName
0,5,44,6,1.0,1,equal_frequency
1,5,44,7,1.0,1,equal_frequency
2,5,44,8,1.0,1,equal_frequency
3,5,44,9,1.1,2,equal_frequency
4,5,44,10,1.1,2,equal_frequency

Composite mode states:
[{'StateID': 1, 'TemporalPropertyID': 44, 'MethodName': 'equal_frequency', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 1.04}, {'StateID': 2, 'TemporalPropertyID': 44, 'MethodName': 'equal_frequency', 'BinId': 2, 'BinLow': 1.04, 'BinHigh': 1.107}, {'StateID': 3, 'TemporalPropertyID': 44, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 1.107, 'BinHigh': inf}, {'StateID': 4, 'TemporalPropertyID': 55, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 0.333, 'BinHigh': inf}, {'StateID': 5, 'TemporalPropertyID': 55, 'MethodName': 'equal_frequency', 'BinId': 2, 'BinLow': 0.0, 'BinHigh': 0.333}, {'StateID': 6, 'TemporalPropertyID': 1, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 7, 'TemporalPropertyID': 1, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 8, 'TemporalPropertyID': 1, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 9, 'TemporalPropertyID': 5, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 20.1, 'BinHigh': inf}, {'StateID': 10, 'TemporalPropertyID': 5, 'MethodName': 'equal_frequency', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 17.067}, {'StateID': 11, 'TemporalPropertyID': 39, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 8.3, 'BinHigh': inf}, {'StateID': 12, 'TemporalPropertyID': 39, 'MethodName': 'equal_frequency', 'BinId': 2, 'BinLow': 6.8, 'BinHigh': 8.3}, {'StateID': 13, 'TemporalPropertyID': 39, 'MethodName': 'equal_frequency', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 6.8}, {'StateID': 14, 'TemporalPropertyID': 40, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 101.0, 'BinHigh': inf}, {'StateID': 15, 'TemporalPropertyID': 40, 'MethodName': 'equal_frequency', 'BinId': 2, 'BinLow': 87.0, 'BinHigh': 101.0}, {'StateID': 16, 'TemporalPropertyID': 40, 'MethodName': 'equal_frequency', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 87.0}, {'StateID': 17, 'TemporalPropertyID': 41, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 173.0, 'BinHigh': inf}, {'StateID': 18, 'TemporalPropertyID': 41, 'MethodName': 'equal_frequency', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 155.0}, {'StateID': 19, 'TemporalPropertyID': 41, 'MethodName': 'equal_frequency', 'BinId': 2, 'BinLow': 155.0, 'BinHigh': 173.0}, {'StateID': 20, 'TemporalPropertyID': 42, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 184.0, 'BinHigh': inf}, {'StateID': 21, 'TemporalPropertyID': 42, 'MethodName': 'equal_frequency', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 126.0}, {'StateID': 22, 'TemporalPropertyID': 42, 'MethodName': 'equal_frequency', 'BinId': 2, 'BinLow': 126.0, 'BinHigh': 184.0}, {'StateID': 23, 'TemporalPropertyID': 43, 'MethodName': 'equal_frequency', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 4.1}, {'StateID': 24, 'TemporalPropertyID': 43, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 4.3, 'BinHigh': inf}, {'StateID': 25, 'TemporalPropertyID': 43, 'MethodName': 'equal_frequency', 'BinId': 2, 'BinLow': 4.1, 'BinHigh': 4.3}, {'StateID': 26, 'TemporalPropertyID': 2, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.0}, {'StateID': 27, 'TemporalPropertyID': 2, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 0.0, 'BinHigh': inf}, {'StateID': 28, 'TemporalPropertyID': 2, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -0.0, 'BinHigh': 0.0}, {'StateID': 29, 'TemporalPropertyID': 3, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 30.0, 'BinHigh': inf}, {'StateID': 30, 'TemporalPropertyID': 3, 'MethodName': 'equal_frequency', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 30.0}, {'StateID': 31, 'TemporalPropertyID': 4, 'MethodName': 'equal_frequency', 'BinId': 2, 'BinLow': 11.0, 'BinHigh': 20.1}, {'StateID': 32, 'TemporalPropertyID': 4, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 20.1, 'BinHigh': inf}, {'StateID': 33, 'TemporalPropertyID': 6, 'MethodName': 'equal_frequency', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 30.0}, {'StateID': 34, 'TemporalPropertyID': 6, 'MethodName': 'equal_frequency', 'BinId': 2, 'BinLow': 30.0, 'BinHigh': 60.0}, {'StateID': 35, 'TemporalPropertyID': 6, 'MethodName': 'equal_frequency', 'BinId': 3, 'BinLow': 60.0, 'BinHigh': inf}]

### 3. Example of Multiple Methods for All Variables (Composite Mode)

In [9]:
method_config = {
    "default": [
         {"method": "sax", "bins": 3},
         {"method": "equal_width", "bins": 4},
         {"method": "gradient", "bins": 3, "gradient_window_size": 180}  # Fixed window size
       ]
}

ta = TemporalAbstraction(data)
final_result, final_states = ta.apply(method_config=method_config,
                                      split_test=False,
                                      save_output=True,
                                      output_dir= os.path.join(output_dir, "multiple_methods"),
                                      max_gap=1)

print("Composite mode (multiple methods for each variable) symbolic series:")
display(final_result.head())
print("Composite mode (multiple methods) states:")
print(type(final_states))
print(final_states)
# convert states to dict of varbile id: [cuttoff1, cutoff2, ...]
# final_states_dict = {k: v for k, v in final_states.items() if isinstance(v, list)}

Results saved in directory: ./output_test_hugobot/multiple_methods
Composite mode (multiple methods for each variable) symbolic series:

,EntityID,TemporalPropertyID,TimeStamp,TemporalPropertyValue,StateID,MethodName
0,5,44,6,1.0,4,equal_width
1,5,44,7,1.0,4,equal_width
2,5,44,8,1.0,4,equal_width
3,5,44,9,1.1,4,equal_width
4,5,44,10,1.1,4,equal_width

Composite mode (multiple methods) states:
<class 'list'>
[{'StateID': 1, 'TemporalPropertyID': 44, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 2, 'TemporalPropertyID': 44, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 3, 'TemporalPropertyID': 44, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 4, 'TemporalPropertyID': 44, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 1.102}, {'StateID': 5, 'TemporalPropertyID': 44, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 1.102, 'BinHigh': 1.335}, {'StateID': 6, 'TemporalPropertyID': 44, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 1.568, 'BinHigh': inf}, {'StateID': 7, 'TemporalPropertyID': 44, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 0.219}, {'StateID': 8, 'TemporalPropertyID': 44, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 0.409, 'BinHigh': inf}, {'StateID': 9, 'TemporalPropertyID': 44, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': 0.219, 'BinHigh': 0.409}, {'StateID': 10, 'TemporalPropertyID': 55, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 11, 'TemporalPropertyID': 55, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 12, 'TemporalPropertyID': 55, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 0.75, 'BinHigh': inf}, {'StateID': 13, 'TemporalPropertyID': 55, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 0.25}, {'StateID': 14, 'TemporalPropertyID': 1, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 15, 'TemporalPropertyID': 1, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 16, 'TemporalPropertyID': 1, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 17, 'TemporalPropertyID': 1, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 30.6}, {'StateID': 18, 'TemporalPropertyID': 1, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 30.6, 'BinHigh': 48.3}, {'StateID': 19, 'TemporalPropertyID': 1, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 48.3, 'BinHigh': 66.0}, {'StateID': 20, 'TemporalPropertyID': 1, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 66.0, 'BinHigh': inf}, {'StateID': 21, 'TemporalPropertyID': 1, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 25.001}, {'StateID': 22, 'TemporalPropertyID': 1, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 41.672, 'BinHigh': inf}, {'StateID': 23, 'TemporalPropertyID': 1, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': 25.001, 'BinHigh': 41.672}, {'StateID': 24, 'TemporalPropertyID': 5, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 25, 'TemporalPropertyID': 5, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 26, 'TemporalPropertyID': 5, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 17.825, 'BinHigh': inf}, {'StateID': 27, 'TemporalPropertyID': 5, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 13.275}, {'StateID': 28, 'TemporalPropertyID': 5, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.0}, {'StateID': 29, 'TemporalPropertyID': 5, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -0.0, 'BinHigh': -0.0}, {'StateID': 30, 'TemporalPropertyID': 5, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': -0.0, 'BinHigh': inf}, {'StateID': 31, 'TemporalPropertyID': 39, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 32, 'TemporalPropertyID': 39, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 33, 'TemporalPropertyID': 39, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 34, 'TemporalPropertyID': 39, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 10.5, 'BinHigh': inf}, {'StateID': 35, 'TemporalPropertyID': 39, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 7.3, 'BinHigh': 8.9}, {'StateID': 36, 'TemporalPropertyID': 39, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 8.9, 'BinHigh': 10.5}, {'StateID': 37, 'TemporalPropertyID': 39, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 7.3}, {'StateID': 38, 'TemporalPropertyID': 39, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': -4.759, 'BinHigh': inf}, {'StateID': 39, 'TemporalPropertyID': 39, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -6.199}, {'StateID': 40, 'TemporalPropertyID': 39, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -6.199, 'BinHigh': -4.759}, {'StateID': 41, 'TemporalPropertyID': 40, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 42, 'TemporalPropertyID': 40, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 43, 'TemporalPropertyID': 40, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 44, 'TemporalPropertyID': 40, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 132.75, 'BinHigh': inf}, {'StateID': 45, 'TemporalPropertyID': 40, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 92.25, 'BinHigh': 112.5}, {'StateID': 46, 'TemporalPropertyID': 40, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 112.5, 'BinHigh': 132.75}, {'StateID': 47, 'TemporalPropertyID': 40, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 92.25}, {'StateID': 48, 'TemporalPropertyID': 40, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 0.0, 'BinHigh': inf}, {'StateID': 49, 'TemporalPropertyID': 40, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -32.04}, {'StateID': 50, 'TemporalPropertyID': 40, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -32.04, 'BinHigh': 0.0}, {'StateID': 51, 'TemporalPropertyID': 41, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 52, 'TemporalPropertyID': 41, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 53, 'TemporalPropertyID': 41, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 54, 'TemporalPropertyID': 41, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 168.75, 'BinHigh': 192.5}, {'StateID': 55, 'TemporalPropertyID': 41, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 216.25, 'BinHigh': inf}, {'StateID': 56, 'TemporalPropertyID': 41, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 192.5, 'BinHigh': 216.25}, {'StateID': 57, 'TemporalPropertyID': 41, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 168.75}, {'StateID': 58, 'TemporalPropertyID': 41, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -0.0, 'BinHigh': 10.443}, {'StateID': 59, 'TemporalPropertyID': 41, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.0}, {'StateID': 60, 'TemporalPropertyID': 41, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 10.443, 'BinHigh': inf}, {'StateID': 61, 'TemporalPropertyID': 42, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 62, 'TemporalPropertyID': 42, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 63, 'TemporalPropertyID': 42, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 64, 'TemporalPropertyID': 42, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 251.25, 'BinHigh': inf}, {'StateID': 65, 'TemporalPropertyID': 42, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 133.75, 'BinHigh': 192.5}, {'StateID': 66, 'TemporalPropertyID': 42, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 192.5, 'BinHigh': 251.25}, {'StateID': 67, 'TemporalPropertyID': 42, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 133.75}, {'StateID': 68, 'TemporalPropertyID': 42, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': -0.0, 'BinHigh': inf}, {'StateID': 69, 'TemporalPropertyID': 42, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -68.227, 'BinHigh': -0.0}, {'StateID': 70, 'TemporalPropertyID': 42, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -68.227}, {'StateID': 71, 'TemporalPropertyID': 43, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 72, 'TemporalPropertyID': 43, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 73, 'TemporalPropertyID': 43, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 74, 'TemporalPropertyID': 43, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 4.0}, {'StateID': 75, 'TemporalPropertyID': 43, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 4.3, 'BinHigh': 4.6}, {'StateID': 76, 'TemporalPropertyID': 43, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 4.6, 'BinHigh': inf}, {'StateID': 77, 'TemporalPropertyID': 43, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 4.0, 'BinHigh': 4.3}, {'StateID': 78, 'TemporalPropertyID': 43, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 0.259}, {'StateID': 79, 'TemporalPropertyID': 43, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 0.637, 'BinHigh': inf}, {'StateID': 80, 'TemporalPropertyID': 43, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': 0.259, 'BinHigh': 0.637}, {'StateID': 81, 'TemporalPropertyID': 2, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 82, 'TemporalPropertyID': 2, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 83, 'TemporalPropertyID': 2, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 17.825, 'BinHigh': inf}, {'StateID': 84, 'TemporalPropertyID': 2, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 13.275}, {'StateID': 85, 'TemporalPropertyID': 2, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.0}, {'StateID': 86, 'TemporalPropertyID': 2, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -0.0, 'BinHigh': 0.0}, {'StateID': 87, 'TemporalPropertyID': 2, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 0.0, 'BinHigh': inf}, {'StateID': 88, 'TemporalPropertyID': 3, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 89, 'TemporalPropertyID': 3, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 90, 'TemporalPropertyID': 3, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 25.25, 'BinHigh': inf}, {'StateID': 91, 'TemporalPropertyID': 3, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 15.75, 'BinHigh': 20.5}, {'StateID': 92, 'TemporalPropertyID': 3, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 15.75}, {'StateID': 93, 'TemporalPropertyID': 3, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 0.0}, {'StateID': 94, 'TemporalPropertyID': 3, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': 0.0, 'BinHigh': 19.905}, {'StateID': 95, 'TemporalPropertyID': 3, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 19.905, 'BinHigh': inf}, {'StateID': 96, 'TemporalPropertyID': 4, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 97, 'TemporalPropertyID': 4, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 98, 'TemporalPropertyID': 4, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 99, 'TemporalPropertyID': 4, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 15.75, 'BinHigh': 20.5}, {'StateID': 100, 'TemporalPropertyID': 4, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 25.25, 'BinHigh': inf}, {'StateID': 101, 'TemporalPropertyID': 4, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 15.75}, {'StateID': 102, 'TemporalPropertyID': 4, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.0}, {'StateID': 103, 'TemporalPropertyID': 4, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -0.0, 'BinHigh': 3.932}, {'StateID': 104, 'TemporalPropertyID': 4, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 3.932, 'BinHigh': inf}, {'StateID': 105, 'TemporalPropertyID': 6, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 106, 'TemporalPropertyID': 6, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 107, 'TemporalPropertyID': 6, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 33.75}, {'StateID': 108, 'TemporalPropertyID': 6, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 52.5, 'BinHigh': 71.25}, {'StateID': 109, 'TemporalPropertyID': 6, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 71.25, 'BinHigh': inf}, {'StateID': 110, 'TemporalPropertyID': 6, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 49.257, 'BinHigh': inf}, {'StateID': 111, 'TemporalPropertyID': 6, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 47.409}, {'StateID': 112, 'TemporalPropertyID': 6, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': 47.409, 'BinHigh': 49.257}]

### 4. Examples of Using Different PAA Methods in Single Mode

In [10]:
from ta_package import TemporalAbstraction

ta = TemporalAbstraction(data)

final_result, final_states = ta.apply(method="sax", bins=3, per_variable=True, 
                                      paa="mean", paa_window=4, 
                                      split_test=False, 
                                      save_output=True,output_dir=os.path.join(output_dir, "paa_mean"), 
                                      max_gap=1)

print("SAX with PAA mean result:")
display(final_result)
print(final_states)

Results saved in directory: ./output_test_hugobot/paa_mean
SAX with PAA mean result:

    EntityID  TemporalPropertyID  TimeStamp  TemporalPropertyValue  state
0          5                   2        3.0                   20.1      3
1          5                   2        8.0                   20.1      3
2          5                   2       12.0                   20.1      3
0          5                   3        3.0                   20.1      1
1          5                   3        8.0                   20.1      1
..       ...                 ...        ...                    ...    ...
6          8                  42       12.0                   75.0      1
7          8                  42       13.0                   75.0      1
8          8                  42       14.0                   75.0      1
9          8                  42       15.0                   75.0      1
10         8                  42       16.0                   75.0      1

[296 rows x 5 columns]

{1: [-0.43072729929545756, 0.43072729929545744], 2: [-0.43072729929545756, 0.43072729929545744], 3: [-0.43072729929545756, 0.43072729929545744], 4: [-0.43072729929545756, 0.43072729929545744], 5: [-0.43072729929545756, 0.43072729929545744], 6: [-0.43072729929545756, 0.43072729929545744], 39: [-0.43072729929545756, 0.43072729929545744], 40: [-0.43072729929545756, 0.43072729929545744], 41: [-0.43072729929545756, 0.43072729929545744], 42: [-0.43072729929545756, 0.43072729929545744], 43: [-0.43072729929545756, 0.43072729929545744], 44: [-0.43072729929545756, 0.43072729929545744], 55: [-0.43072729929545756, 0.43072729929545744]}

### 5. Knowledge Base Example

In [11]:
from ta_package import TemporalAbstraction
from ta_package.utils import split_train_test

train_data, test_data = split_train_test(data, train_ratio=0.8)

ta = TemporalAbstraction(train_data)

train_results, train_states = ta.apply(method="sax", bins=3, per_variable=True, 
                                      paa="mean", paa_window=4, 
                                      split_test=False, 
                                      save_output=True,output_dir=os.path.join(output_dir, "train_sax"), 
                                      max_gap=1)

test_ta = TemporalAbstraction(test_data)

test_results, test_states = test_ta.apply(method = "knowledge", train_states=train_states,
                         split_test=False, 
                         save_output=True, output_dir=os.path.join(output_dir, "knowledge_test"),
                         max_gap=1)

Results saved in directory: ./output_test_hugobot/train_sax
Results saved in directory: ./output_test_hugobot/knowledge_test

In [12]:
ta = TemporalAbstraction(data)

final_result, final_states = ta.apply(method="equal_width", bins=3, per_variable=True, 
                                      paa="max", paa_window=4,
                                      split_test=False, 
                                      save_output=True, output_dir=os.path.join(output_dir, "paa_max"), 
                                      max_gap=1)

print("EqualWidth with PAA max result:")
display(final_result)

Results saved in directory: ./output_test_hugobot/paa_max
EqualWidth with PAA max result:

    EntityID  TemporalPropertyID  TimeStamp  TemporalPropertyValue  state
0          5                   2        3.0                   20.1      3
1          5                   2        8.0                   20.1      3
2          5                   2       12.0                   20.1      3
0          5                   3        3.0                   20.1      1
1          5                   3        8.0                   20.1      1
..       ...                 ...        ...                    ...    ...
6          8                  42       12.0                   75.0      1
7          8                  42       13.0                   75.0      1
8          8                  42       14.0                   75.0      1
9          8                  42       15.0                   75.0      1
10         8                  42       16.0                   75.0      1

[296 rows x 5 columns]

### 6. Examples of Train-Test Splitting

In [13]:
ta = TemporalAbstraction(data)

# Using Gradient in single-method mode with train-test split.
(final_train, final_test), final_states = ta.apply(method="gradient",
                                                   bins=3,
                                                   per_variable=True,
                                                   gradient_window_size=180,  # Fixed window size
                                                   split_test=True,
                                                   paa="mean",
                                                   paa_window=5,
                                                   save_output=True,
                                                   output_dir=os.path.join(output_dir, "train_test_gradient"),
                                                   max_gap=1,train_ratio=0.8)

print("Train set (Gradient):")
display(final_train.head())
print("Test set (Gradient):")
display(final_test.head())

Results saved in directory: ./output_test_hugobot/train_test_gradient\train
Results saved in directory: ./output_test_hugobot/train_test_gradient\test
Train set (Gradient):

,EntityID,TemporalPropertyID,TimeStamp,TemporalPropertyValue,angle,state
0,5,2,2.0,20.1,NaN,-1
1,5,2,7.0,20.1,1.398025e-14,2
0,5,3,2.0,20.1,NaN,-1
1,5,3,7.0,20.1,1.398025e-14,1
0,5,4,2.0,20.1,NaN,-1

Test set (Gradient):

,EntityID,TemporalPropertyID,TimeStamp,TemporalPropertyValue,angle,state
0,8,1,2.0,25.0,NaN,-1
0,8,6,2.0,28.0,NaN,-1
0,8,40,5.0,101.0,NaN,-1
1,8,40,6.0,101.0,-5.212522e-13,3
2,8,40,7.0,101.0,6.210642e-13,3

In [14]:
# from ta_package import TemporalAbstraction
# data = pd.read_csv(r"C:\Users\User\Master_Files\Hugobot\beta-release-v1.0.1_21-07-2019\Datasets\falls_85-90_all_vars_only_class_1.csv")
# ta = TemporalAbstraction(data)
# # Use the high-level API to apply gradient (single-method mode).
# final_result, final_states = ta.apply(method="gradient", bins=3, per_variable=True,paa="mean", paa_window=1, gradient_window_size=3,split_test=False,save_output=True, output_dir= os.path.join(output_dir, "gradient"),max_gap=20)
# print("High-level gradient result:")
# display(final_result.head())
# print("High-level gradient states:")
# print(final_states)

### 7. Composite Mode Example Knowledge Base

In [15]:
from ta_package import TemporalAbstraction


print(f"\nRunning Hugobot abstraction on training data...")

train_data_file = "train_new.csv"
train_df = pd.read_csv(train_data_file, low_memory=False)

train_ta = TemporalAbstraction(train_df)
d_method = "td4c"
num_of_bins = 3
interpolation_gap =45

# Use the high-level API to apply SAX (single-method mode).
final_result, final_states = train_ta.apply(method=d_method, bins=3, per_variable=True, 
                                      paa="mean", paa_window=5,
                                      split_test=False, 
                                      save_output=True, output_dir= os.path.join(output_dir, "sax"), 
                                      max_gap=1)

print("High-level td4c result:")
display(final_result.head())
print("High-level td4c states:")
print(final_states)

Running Hugobot abstraction on training data...

Warning: about to remove 121 rows containing NaNs in TemporalPropertyValue

KeyboardInterrupt:

In [24]:
from ta_package import TemporalAbstraction
import warnings
import numpy as np
import pandas as pd
import os

data = pd.read_csv("FAGender.csv")
output_dir = "./output_test_hugobot/"


print(f"\nRunning Hugobot abstraction on training data...")

train_data_file = "train.csv"
train_df = pd.read_csv(train_data_file, low_memory=False)
train_df = train_df[:1000]
train_ta = TemporalAbstraction(train_df)
d_method = "equal_width"
num_of_bins = 3
interpolation_gap = 2

# where entity id is 0 change to max(entitiyID) +1 
# train_df["EntityID"] = train_df["EntityID"].replace(0, train_df["EntityID"].max() + 1)

method_config = {
    "default": [
         {"method": "td4c", "bins": 4},
         {"method": "gradient", "bins": 3, "gradient_window_size": 3}  
       ]
}

results, train_states = train_ta.apply(method_config=method_config,
                                per_variable=True,
                                split_test=False,
                                save_output=True,
                                output_dir=os.path.join(output_dir, "Train_Eldar"),
                                max_gap=interpolation_gap)



print(f"\nRunning knowledge-based abstraction on test data...")

Running Hugobot abstraction on training data...
Warning: Not enough variability in for TemporalPropertyID 57 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 7 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 10 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 33 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 47 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 2 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 6 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 13 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 15 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 16 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 29 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 41 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 60 for cutpoints. Using default candidates.
Warning: Not enough variability in for TemporalPropertyID 55 for cutpoints. Using default candidates.
Results saved in directory: ./output_test_hugobot/Train_Eldar

Running knowledge-based abstraction on test data...

In [26]:
# from ta_package import utils
# test_data_file = "test_new.csv"
# test_df = pd.read_csv(test_data_file)

# test_df = utils.map_states_to_test_composite(test_df, train_states, method_config, output_dir = os.path.join(output_dir, "Test") , max_gap = interpolation_gap)
# test_df.head()

### 8. Skipping Variables Example

```python

In [27]:
skip_var = [42 , 43]

train_data_file = "train.csv"
from ta_package import TemporalAbstraction
method_config = {
    "default": [
         {"method": "sax", "bins": 3},
         {"method": "equal_width", "bins": 4},
         {"method": "gradient", "bins": 3, "gradient_window_size": 180}  # Fixed window size
       ]
}

ta = TemporalAbstraction(data)
final_result, final_states = ta.apply(method_config=method_config,
                                      split_test=False,
                                      save_output=True,
                                      output_dir= os.path.join(output_dir, "multiple_methods"),
                                      max_gap=1, skip_var=skip_var)

print("Composite mode (multiple methods for each variable) symbolic series:")
display(final_result.head())
print("Composite mode (multiple methods) states:")
print(type(final_states))
print(final_states)
# convert states to dict of varbile id: [cuttoff1, cutoff2, ...]
# final_states_dict = {k: v for k, v in final_states.items() if isinstance(v, list)}

Skipping variables: [42, 43]
Results saved in directory: ./output_test_hugobot/multiple_methods
Composite mode (multiple methods for each variable) symbolic series:

,EntityID,TemporalPropertyID,TimeStamp,TemporalPropertyValue,StateID,MethodName
0,5,44,6,1.0,4.0,equal_width
1,5,44,7,1.0,4.0,equal_width
2,5,44,8,1.0,4.0,equal_width
3,5,44,9,1.1,4.0,equal_width
4,5,44,10,1.1,4.0,equal_width

Composite mode (multiple methods) states:
<class 'list'>
[{'StateID': 1, 'TemporalPropertyID': 44, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 2, 'TemporalPropertyID': 44, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 3, 'TemporalPropertyID': 44, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 4, 'TemporalPropertyID': 44, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 1.102}, {'StateID': 5, 'TemporalPropertyID': 44, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 1.102, 'BinHigh': 1.335}, {'StateID': 6, 'TemporalPropertyID': 44, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 1.568, 'BinHigh': inf}, {'StateID': 7, 'TemporalPropertyID': 44, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 0.219}, {'StateID': 8, 'TemporalPropertyID': 44, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 0.409, 'BinHigh': inf}, {'StateID': 9, 'TemporalPropertyID': 44, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': 0.219, 'BinHigh': 0.409}, {'StateID': 10, 'TemporalPropertyID': 55, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 11, 'TemporalPropertyID': 55, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 12, 'TemporalPropertyID': 55, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 0.75, 'BinHigh': inf}, {'StateID': 13, 'TemporalPropertyID': 55, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 0.25}, {'StateID': 14, 'TemporalPropertyID': 1, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 15, 'TemporalPropertyID': 1, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 16, 'TemporalPropertyID': 1, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 17, 'TemporalPropertyID': 1, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 30.6}, {'StateID': 18, 'TemporalPropertyID': 1, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 30.6, 'BinHigh': 48.3}, {'StateID': 19, 'TemporalPropertyID': 1, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 48.3, 'BinHigh': 66.0}, {'StateID': 20, 'TemporalPropertyID': 1, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 66.0, 'BinHigh': inf}, {'StateID': 21, 'TemporalPropertyID': 1, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 25.001}, {'StateID': 22, 'TemporalPropertyID': 1, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 41.672, 'BinHigh': inf}, {'StateID': 23, 'TemporalPropertyID': 1, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': 25.001, 'BinHigh': 41.672}, {'StateID': 24, 'TemporalPropertyID': 5, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 25, 'TemporalPropertyID': 5, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 26, 'TemporalPropertyID': 5, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 17.825, 'BinHigh': inf}, {'StateID': 27, 'TemporalPropertyID': 5, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 13.275}, {'StateID': 28, 'TemporalPropertyID': 5, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.0}, {'StateID': 29, 'TemporalPropertyID': 5, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -0.0, 'BinHigh': -0.0}, {'StateID': 30, 'TemporalPropertyID': 5, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': -0.0, 'BinHigh': inf}, {'StateID': 31, 'TemporalPropertyID': 39, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 32, 'TemporalPropertyID': 39, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 33, 'TemporalPropertyID': 39, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 34, 'TemporalPropertyID': 39, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 10.5, 'BinHigh': inf}, {'StateID': 35, 'TemporalPropertyID': 39, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 7.3, 'BinHigh': 8.9}, {'StateID': 36, 'TemporalPropertyID': 39, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 8.9, 'BinHigh': 10.5}, {'StateID': 37, 'TemporalPropertyID': 39, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 7.3}, {'StateID': 38, 'TemporalPropertyID': 39, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': -4.759, 'BinHigh': inf}, {'StateID': 39, 'TemporalPropertyID': 39, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -6.199}, {'StateID': 40, 'TemporalPropertyID': 39, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -6.199, 'BinHigh': -4.759}, {'StateID': 41, 'TemporalPropertyID': 40, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 42, 'TemporalPropertyID': 40, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 43, 'TemporalPropertyID': 40, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 44, 'TemporalPropertyID': 40, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 132.75, 'BinHigh': inf}, {'StateID': 45, 'TemporalPropertyID': 40, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 92.25, 'BinHigh': 112.5}, {'StateID': 46, 'TemporalPropertyID': 40, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 112.5, 'BinHigh': 132.75}, {'StateID': 47, 'TemporalPropertyID': 40, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 92.25}, {'StateID': 48, 'TemporalPropertyID': 40, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 0.0, 'BinHigh': inf}, {'StateID': 49, 'TemporalPropertyID': 40, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -32.04}, {'StateID': 50, 'TemporalPropertyID': 40, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -32.04, 'BinHigh': 0.0}, {'StateID': 51, 'TemporalPropertyID': 41, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 52, 'TemporalPropertyID': 41, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 53, 'TemporalPropertyID': 41, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 54, 'TemporalPropertyID': 41, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 168.75, 'BinHigh': 192.5}, {'StateID': 55, 'TemporalPropertyID': 41, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 216.25, 'BinHigh': inf}, {'StateID': 56, 'TemporalPropertyID': 41, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 192.5, 'BinHigh': 216.25}, {'StateID': 57, 'TemporalPropertyID': 41, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 168.75}, {'StateID': 58, 'TemporalPropertyID': 41, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -0.0, 'BinHigh': 10.443}, {'StateID': 59, 'TemporalPropertyID': 41, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.0}, {'StateID': 60, 'TemporalPropertyID': 41, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 10.443, 'BinHigh': inf}, {'StateID': 61, 'TemporalPropertyID': 2, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 62, 'TemporalPropertyID': 2, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 63, 'TemporalPropertyID': 2, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 17.825, 'BinHigh': inf}, {'StateID': 64, 'TemporalPropertyID': 2, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 13.275}, {'StateID': 65, 'TemporalPropertyID': 2, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.0}, {'StateID': 66, 'TemporalPropertyID': 2, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -0.0, 'BinHigh': 0.0}, {'StateID': 67, 'TemporalPropertyID': 2, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 0.0, 'BinHigh': inf}, {'StateID': 68, 'TemporalPropertyID': 3, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 69, 'TemporalPropertyID': 3, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 70, 'TemporalPropertyID': 3, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 25.25, 'BinHigh': inf}, {'StateID': 71, 'TemporalPropertyID': 3, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 15.75, 'BinHigh': 20.5}, {'StateID': 72, 'TemporalPropertyID': 3, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 15.75}, {'StateID': 73, 'TemporalPropertyID': 3, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 0.0}, {'StateID': 74, 'TemporalPropertyID': 3, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': 0.0, 'BinHigh': 19.905}, {'StateID': 75, 'TemporalPropertyID': 3, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 19.905, 'BinHigh': inf}, {'StateID': 76, 'TemporalPropertyID': 4, 'MethodName': 'sax', 'BinId': 2, 'BinLow': -0.431, 'BinHigh': 0.431}, {'StateID': 77, 'TemporalPropertyID': 4, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 78, 'TemporalPropertyID': 4, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 79, 'TemporalPropertyID': 4, 'MethodName': 'equal_width', 'BinId': 2, 'BinLow': 15.75, 'BinHigh': 20.5}, {'StateID': 80, 'TemporalPropertyID': 4, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 25.25, 'BinHigh': inf}, {'StateID': 81, 'TemporalPropertyID': 4, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 15.75}, {'StateID': 82, 'TemporalPropertyID': 4, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.0}, {'StateID': 83, 'TemporalPropertyID': 4, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': -0.0, 'BinHigh': 3.932}, {'StateID': 84, 'TemporalPropertyID': 4, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 3.932, 'BinHigh': inf}, {'StateID': 85, 'TemporalPropertyID': 6, 'MethodName': 'sax', 'BinId': 1, 'BinLow': -inf, 'BinHigh': -0.431}, {'StateID': 86, 'TemporalPropertyID': 6, 'MethodName': 'sax', 'BinId': 3, 'BinLow': 0.431, 'BinHigh': inf}, {'StateID': 87, 'TemporalPropertyID': 6, 'MethodName': 'equal_width', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 33.75}, {'StateID': 88, 'TemporalPropertyID': 6, 'MethodName': 'equal_width', 'BinId': 3, 'BinLow': 52.5, 'BinHigh': 71.25}, {'StateID': 89, 'TemporalPropertyID': 6, 'MethodName': 'equal_width', 'BinId': 4, 'BinLow': 71.25, 'BinHigh': inf}, {'StateID': 90, 'TemporalPropertyID': 6, 'MethodName': 'gradient', 'BinId': 3, 'BinLow': 49.257, 'BinHigh': inf}, {'StateID': 91, 'TemporalPropertyID': 6, 'MethodName': 'gradient', 'BinId': 1, 'BinLow': -inf, 'BinHigh': 47.409}, {'StateID': 92, 'TemporalPropertyID': 6, 'MethodName': 'gradient', 'BinId': 2, 'BinLow': 47.409, 'BinHigh': 49.257}]

In [16]:
states = pd.read_csv("icu_KB_states.csv")
icu_data = pd.read_csv("icu_no_zeros.csv")
 
from ta_package import TemporalAbstraction
ta = TemporalAbstraction(icu_data)

final_result, final_states = ta.apply(method="knowledge", train_states =states, output_dir= os.path.join(output_dir, "knowledge"),
                                      max_gap=35)

    StateID  TemporalPropertyID TemporalPropertyName  BinID BinLabel  \
0         1                   1                 ABPm      0      Low
1         2                   1                 ABPm      1   Medium
2         3                   1                 ABPm      2     High
3         4                   2                  CVD      0      Low
4         5                   2                  CVD      1   Medium
5         6                   2                  CVD      2     High
6         7                   3                 FiO2      0      Low
7         8                   3                 FiO2      1   Medium
8         9                   3                 FiO2      2     High
9        10                   4                   Hf      0      Low
10       11                   4                   Hf      1   Medium
11       12                   4                   Hf      2     High
12       13                   5                Mpeep      0      Low
13       14                   5                Mpeep      1     High
14       15                   6                 Temp      0      Low
15       16                   6                 Temp      1   Medium
16       17                   6                 Temp      2     High
17       18                   7                   BE      0      Low
18       19                   7                   BE      1   Medium
19       20                   7                   BE      2     High
20       21                   8                   CI      0      Low
21       22                   8                   CI      1     High
22       23                   9              Glucose      0      Low
23       24                   9              Glucose      1   Medium
24       25                   9              Glucose      2     High
25       26                  10                 CKMB      0      Low
26       27                  10                 CKMB      1   Medium
27       28                  10                 CKMB      2     High

           BinLow  BinHigh
0            -inf     60.0
1              60     90.0
2              90      inf
3            -inf      5.0
4               5     17.0
5              17      inf
6            -inf     41.0
7              41     60.0
8              60      inf
9            -inf     60.0
10             60    110.0
11            110      inf
12           -inf     10.0
13             10      inf
14           -inf     35.0
15             35     38.5
16           38.5      inf
17  -inf.29999924     -6.0
18             -6     -3.0
19             -3      inf
20           -inf      2.5
21            2.5      inf
22           -inf      2.5
23            2.5     10.0
24             10      inf
25           -inf     25.0
26             25     50.0
27             50      inf
Results saved in directory: ./output_test_hugobot/knowledge

In [10]:
train_states = pd.read_csv(r"C:\Users\User\Master_Files\Hugobot\beta-release-v1.0.1_21-07-2019\Hugobot2\AKI_KB_states_22_variables.csv")


data =  pd.read_csv(r"C:\Users\User\Master_Files\Hugobot\beta-release-v1.0.1_21-07-2019\Hugobot2\train 2.csv")


gradient_cutoffs = {
    1: [-20, 20],    # Variable 1
    2: [-20,20],    # Variable 2
    3: [-20,20],    # Variable 3
    4: [-50,50],    # Variable 4
    5: [-10,10],    # Variable 5
    50811: [-30,30],    # Variable 5081
    51222: [-30,30],    # Variable 51222
    50813: [-50,50],    # Variable 50813

}



method_config = {
    "default": [
        {
                "method": "knowledge",
                "states": train_states  # Pass the CSV here!
            },
         {"method": "equal_width", "bins": 4},
         {
                "method": "gradient",
                "gradient_window_size": 120,  # 2 hours - captures dynamic trends without over-smoothing
                "sub_method": "knowledge",
                "knowledge_cutoffs": gradient_cutoffs,  # Pass ENTIRE dict - system looks up each variable's cutoffs
                "bins": 3,
            } # Fixed window size
       ]
}
ta = TemporalAbstraction(data)

# # single method knowledge-based test
# test_results, test_states = ta.apply(method = "knowledge", train_states=train_states,
#                          split_test=False, 
#                          save_output=True, output_dir=os.path.join(output_dir, "knowledge_test"),
#                          max_gap=45)


# multiple methods test
final_result, final_states = ta.apply(method_config=method_config,
                                      split_test=False,
                                      save_output=True,
                                      output_dir= os.path.join(output_dir, "multiple_methods"),
                                      max_gap=45)

Warning: about to remove 78 rows containing NaNs in TemporalPropertyValue
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 7.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 6.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 50804.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 50822.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 50882.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 50902.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 50912.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 50971.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 50983.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 51006.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 50806.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 50824.
Warning: Knowledge cutoffs not properly defined. not mapping gradient abstraction for 51491.
Results saved in directory: ./output_test_hugobot/multiple_methods

In [11]:
final_states

[{'StateID': 1,
  'TemporalPropertyID': 1,
  'TemporalPropertyName': 'Heart Rate',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 40.0},
 {'StateID': 2,
  'TemporalPropertyID': 1,
  'TemporalPropertyName': 'Heart Rate',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '40',
  'BinHigh': 60.0},
 {'StateID': 3,
  'TemporalPropertyID': 1,
  'TemporalPropertyName': 'Heart Rate',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '60',
  'BinHigh': 100.0},
 {'StateID': 4,
  'TemporalPropertyID': 1,
  'TemporalPropertyName': 'Heart Rate',
  'MethodName': 'knowledge',
  'BinId': 4,
  'BinLabel': '',
  'BinLow': '100',
  'BinHigh': inf},
 {'StateID': 5,
  'TemporalPropertyID': 2,
  'TemporalPropertyName': 'Non Invasive Blood Pressure systolic',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 90.0},
 {'StateID': 6,
  'TemporalPropertyID': 2,
  'TemporalPropertyName': 'Non Invasive Blood Pressure systolic',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '90',
  'BinHigh': 120.0},
 {'StateID': 7,
  'TemporalPropertyID': 2,
  'TemporalPropertyName': 'Non Invasive Blood Pressure systolic',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '120',
  'BinHigh': inf},
 {'StateID': 8,
  'TemporalPropertyID': 3,
  'TemporalPropertyName': 'Non Invasive Blood Pressure diastolic',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 60.0},
 {'StateID': 9,
  'TemporalPropertyID': 3,
  'TemporalPropertyName': 'Non Invasive Blood Pressure diastolic',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '60',
  'BinHigh': 90.0},
 {'StateID': 10,
  'TemporalPropertyID': 3,
  'TemporalPropertyName': 'Non Invasive Blood Pressure diastolic',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '90',
  'BinHigh': inf},
 {'StateID': 11,
  'TemporalPropertyID': 4,
  'TemporalPropertyName': 'Respiratory Rate',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 12.0},
 {'StateID': 12,
  'TemporalPropertyID': 4,
  'TemporalPropertyName': 'Respiratory Rate',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '12',
  'BinHigh': 20.0},
 {'StateID': 13,
  'TemporalPropertyID': 4,
  'TemporalPropertyName': 'Respiratory Rate',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '20',
  'BinHigh': inf},
 {'StateID': 14,
  'TemporalPropertyID': 5,
  'TemporalPropertyName': 'O2 saturation pulseoxymetry',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 92.0},
 {'StateID': 15,
  'TemporalPropertyID': 5,
  'TemporalPropertyName': 'O2 saturation pulseoxymetry',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '92',
  'BinHigh': 100.0},
 {'StateID': 16,
  'TemporalPropertyID': 5,
  'TemporalPropertyName': 'O2 saturation pulseoxymetry',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '100',
  'BinHigh': inf},
 {'StateID': 20,
  'TemporalPropertyID': 7,
  'TemporalPropertyName': 'Urine output (Foley)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 800.0},
 {'StateID': 21,
  'TemporalPropertyID': 7,
  'TemporalPropertyName': 'Urine output (Foley)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '800',
  'BinHigh': 2000.0},
 {'StateID': 22,
  'TemporalPropertyID': 7,
  'TemporalPropertyName': 'Urine output (Foley)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '2000',
  'BinHigh': inf},
 {'StateID': 17,
  'TemporalPropertyID': 6,
  'TemporalPropertyName': 'Temperature',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 36.0},
 {'StateID': 18,
  'TemporalPropertyID': 6,
  'TemporalPropertyName': 'Temperature',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '36',
  'BinHigh': 38.0},
 {'StateID': 19,
  'TemporalPropertyID': 6,
  'TemporalPropertyName': 'Temperature',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '38',
  'BinHigh': inf},
 {'StateID': 47,
  'TemporalPropertyID': 50804,
  'TemporalPropertyName': 'Total CO2',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 22.0},
 {'StateID': 48,
  'TemporalPropertyID': 50804,
  'TemporalPropertyName': 'Total CO2',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '22',
  'BinHigh': 26.0},
 {'StateID': 49,
  'TemporalPropertyID': 50804,
  'TemporalPropertyName': 'Total CO2',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '26',
  'BinHigh': inf},
 {'StateID': 50,
  'TemporalPropertyID': 50811,
  'TemporalPropertyName': 'Hemoglobin (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 12.0},
 {'StateID': 51,
  'TemporalPropertyID': 50811,
  'TemporalPropertyName': 'Hemoglobin (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '12',
  'BinHigh': 18.0},
 {'StateID': 52,
  'TemporalPropertyID': 50811,
  'TemporalPropertyName': 'Hemoglobin (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '18',
  'BinHigh': inf},
 {'StateID': 41,
  'TemporalPropertyID': 50822,
  'TemporalPropertyName': 'Potassium (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 3.6},
 {'StateID': 42,
  'TemporalPropertyID': 50822,
  'TemporalPropertyName': 'Potassium (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '3.6',
  'BinHigh': 5.2},
 {'StateID': 43,
  'TemporalPropertyID': 50822,
  'TemporalPropertyName': 'Potassium (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '5.2',
  'BinHigh': inf},
 {'StateID': 26,
  'TemporalPropertyID': 50882,
  'TemporalPropertyName': 'Bicarbonate (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 22.0},
 {'StateID': 27,
  'TemporalPropertyID': 50882,
  'TemporalPropertyName': 'Bicarbonate (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '22',
  'BinHigh': 26.0},
 {'StateID': 28,
  'TemporalPropertyID': 50882,
  'TemporalPropertyName': 'Bicarbonate (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '26',
  'BinHigh': inf},
 {'StateID': 56,
  'TemporalPropertyID': 50902,
  'TemporalPropertyName': 'Chloride (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 96.0},
 {'StateID': 57,
  'TemporalPropertyID': 50902,
  'TemporalPropertyName': 'Chloride (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '96',
  'BinHigh': 106.0},
 {'StateID': 58,
  'TemporalPropertyID': 50902,
  'TemporalPropertyName': 'Chloride (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '106',
  'BinHigh': inf},
 {'StateID': 29,
  'TemporalPropertyID': 50912,
  'TemporalPropertyName': 'Creatinine (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 1.3},
 {'StateID': 30,
  'TemporalPropertyID': 50912,
  'TemporalPropertyName': 'Creatinine (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '1.3',
  'BinHigh': 2.0},
 {'StateID': 31,
  'TemporalPropertyID': 50912,
  'TemporalPropertyName': 'Creatinine (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '2',
  'BinHigh': inf},
 {'StateID': 44,
  'TemporalPropertyID': 50971,
  'TemporalPropertyName': 'Potassium (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 3.6},
 {'StateID': 45,
  'TemporalPropertyID': 50971,
  'TemporalPropertyName': 'Potassium (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '3.6',
  'BinHigh': 5.2},
 {'StateID': 46,
  'TemporalPropertyID': 50971,
  'TemporalPropertyName': 'Potassium (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '5.2',
  'BinHigh': inf},
 {'StateID': 38,
  'TemporalPropertyID': 50983,
  'TemporalPropertyName': 'Sodium (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 135.0},
 {'StateID': 39,
  'TemporalPropertyID': 50983,
  'TemporalPropertyName': 'Sodium (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '135',
  'BinHigh': 145.0},
 {'StateID': 40,
  'TemporalPropertyID': 50983,
  'TemporalPropertyName': 'Sodium (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '145',
  'BinHigh': inf},
 {'StateID': 32,
  'TemporalPropertyID': 51006,
  'TemporalPropertyName': 'Urea Nitrogen (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 6.0},
 {'StateID': 33,
  'TemporalPropertyID': 51006,
  'TemporalPropertyName': 'Urea Nitrogen (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '6',
  'BinHigh': 24.0},
 {'StateID': 34,
  'TemporalPropertyID': 51006,
  'TemporalPropertyName': 'Urea Nitrogen (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '24',
  'BinHigh': inf},
 {'StateID': 53,
  'TemporalPropertyID': 51222,
  'TemporalPropertyName': 'Hemoglobin (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 12.0},
 {'StateID': 54,
  'TemporalPropertyID': 51222,
  'TemporalPropertyName': 'Hemoglobin (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '12',
  'BinHigh': 18.0},
 {'StateID': 55,
  'TemporalPropertyID': 51222,
  'TemporalPropertyName': 'Hemoglobin (Chemistry)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '18',
  'BinHigh': inf},
 {'StateID': 65,
  'TemporalPropertyID': 50813,
  'TemporalPropertyName': 'Lactate',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 0.5},
 {'StateID': 66,
  'TemporalPropertyID': 50813,
  'TemporalPropertyName': 'Lactate',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '0.5',
  'BinHigh': 2.2},
 {'StateID': 67,
  'TemporalPropertyID': 50813,
  'TemporalPropertyName': 'Lactate',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '2.2',
  'BinHigh': inf},
 {'StateID': 59,
  'TemporalPropertyID': 50806,
  'TemporalPropertyName': 'Chloride (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 96.0},
 {'StateID': 60,
  'TemporalPropertyID': 50806,
  'TemporalPropertyName': 'Chloride (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '96',
  'BinHigh': 106.0},
 {'StateID': 61,
  'TemporalPropertyID': 50806,
  'TemporalPropertyName': 'Chloride (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '106',
  'BinHigh': inf},
 {'StateID': 35,
  'TemporalPropertyID': 50824,
  'TemporalPropertyName': 'Sodium (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 135.0},
 {'StateID': 36,
  'TemporalPropertyID': 50824,
  'TemporalPropertyName': 'Sodium (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '135',
  'BinHigh': 145.0},
 {'StateID': 37,
  'TemporalPropertyID': 50824,
  'TemporalPropertyName': 'Sodium (Blood Gas)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '145',
  'BinHigh': inf},
 {'StateID': 62,
  'TemporalPropertyID': 51491,
  'TemporalPropertyName': 'PH (Urine)',
  'MethodName': 'knowledge',
  'BinId': 1,
  'BinLabel': '',
  'BinLow': '#NAME?',
  'BinHigh': 7.35},
 {'StateID': 63,
  'TemporalPropertyID': 51491,
  'TemporalPropertyName': 'PH (Urine)',
  'MethodName': 'knowledge',
  'BinId': 2,
  'BinLabel': '',
  'BinLow': '7.35',
  'BinHigh': 7.45},
 {'StateID': 64,
  'TemporalPropertyID': 51491,
  'TemporalPropertyName': 'PH (Urine)',
  'MethodName': 'knowledge',
  'BinId': 3,
  'BinLabel': '',
  'BinLow': '7.45',
  'BinHigh': inf},
 {'StateID': 68,
  'TemporalPropertyID': 1,
  'MethodName': 'equal_width',
  'BinId': 2,
  'BinLow': 52.25,
  'BinHigh': 104.5},
 {'StateID': 69,
  'TemporalPropertyID': 1,
  'MethodName': 'equal_width',
  'BinId': 3,
  'BinLow': 104.5,
  'BinHigh': 156.75},
 {'StateID': 70,
  'TemporalPropertyID': 1,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': 52.25},
 {'StateID': 71,
  'TemporalPropertyID': 1,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 156.75,
  'BinHigh': inf},
 {'StateID': 72,
  'TemporalPropertyID': 1,
  'MethodName': 'gradient',
  'BinId': 2,
  'BinLow': -20,
  'BinHigh': 20},
 {'StateID': 73,
  'TemporalPropertyID': 1,
  'MethodName': 'gradient',
  'BinId': 3,
  'BinLow': 20,
  'BinHigh': inf},
 {'StateID': 74,
  'TemporalPropertyID': 1,
  'MethodName': 'gradient',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': -20},
 {'StateID': 75,
  'TemporalPropertyID': 2,
  'MethodName': 'equal_width',
  'BinId': 2,
  'BinLow': 74.0,
  'BinHigh': 148.0},
 {'StateID': 76,
  'TemporalPropertyID': 2,
  'MethodName': 'equal_width',
  'BinId': 3,
  'BinLow': 148.0,
  'BinHigh': 222.0},
 {'StateID': 77,
  'TemporalPropertyID': 2,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': 74.0},
 {'StateID': 78,
  'TemporalPropertyID': 2,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 222.0,
  'BinHigh': inf},
 {'StateID': 79,
  'TemporalPropertyID': 2,
  'MethodName': 'gradient',
  'BinId': 2,
  'BinLow': -20,
  'BinHigh': 20},
 {'StateID': 80,
  'TemporalPropertyID': 2,
  'MethodName': 'gradient',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': -20},
 {'StateID': 81,
  'TemporalPropertyID': 2,
  'MethodName': 'gradient',
  'BinId': 3,
  'BinLow': 20,
  'BinHigh': inf},
 {'StateID': 82,
  'TemporalPropertyID': 3,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': 1687.5},
 {'StateID': 83,
  'TemporalPropertyID': 3,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 5062.5,
  'BinHigh': inf},
 {'StateID': 84,
  'TemporalPropertyID': 3,
  'MethodName': 'gradient',
  'BinId': 2,
  'BinLow': -20,
  'BinHigh': 20},
 {'StateID': 85,
  'TemporalPropertyID': 3,
  'MethodName': 'gradient',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': -20},
 {'StateID': 86,
  'TemporalPropertyID': 3,
  'MethodName': 'gradient',
  'BinId': 3,
  'BinLow': 20,
  'BinHigh': inf},
 {'StateID': 87,
  'TemporalPropertyID': 4,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': 24.75},
 {'StateID': 88,
  'TemporalPropertyID': 4,
  'MethodName': 'equal_width',
  'BinId': 2,
  'BinLow': 24.75,
  'BinHigh': 49.5},
 {'StateID': 89,
  'TemporalPropertyID': 4,
  'MethodName': 'equal_width',
  'BinId': 3,
  'BinLow': 49.5,
  'BinHigh': 74.25},
 {'StateID': 90,
  'TemporalPropertyID': 4,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 74.25,
  'BinHigh': inf},
 {'StateID': 91,
  'TemporalPropertyID': 4,
  'MethodName': 'gradient',
  'BinId': 2,
  'BinLow': -50,
  'BinHigh': 50},
 {'StateID': 92,
  'TemporalPropertyID': 4,
  'MethodName': 'gradient',
  'BinId': 3,
  'BinLow': 50,
  'BinHigh': inf},
 {'StateID': 93,
  'TemporalPropertyID': 4,
  'MethodName': 'gradient',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': -50},
 {'StateID': 94,
  'TemporalPropertyID': 5,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 76.0,
  'BinHigh': inf},
 {'StateID': 95,
  'TemporalPropertyID': 5,
  'MethodName': 'equal_width',
  'BinId': 3,
  'BinLow': 52.0,
  'BinHigh': 76.0},
 {'StateID': 96,
  'TemporalPropertyID': 5,
  'MethodName': 'equal_width',
  'BinId': 2,
  'BinLow': 28.0,
  'BinHigh': 52.0},
 {'StateID': 97,
  'TemporalPropertyID': 5,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': 28.0},
 {'StateID': 98,
  'TemporalPropertyID': 5,
  'MethodName': 'gradient',
  'BinId': 2,
  'BinLow': -10,
  'BinHigh': 10},
 {'StateID': 99,
  'TemporalPropertyID': 5,
  'MethodName': 'gradient',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': -10},
 {'StateID': 100,
  'TemporalPropertyID': 5,
  'MethodName': 'gradient',
  'BinId': 3,
  'BinLow': 10,
  'BinHigh': inf},
 {'StateID': 101,
  'TemporalPropertyID': 7,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': 300.0},
 {'StateID': 102,
  'TemporalPropertyID': 7,
  'MethodName': 'equal_width',
  'BinId': 2,
  'BinLow': 300.0,
  'BinHigh': 600.0},
 {'StateID': 103,
  'TemporalPropertyID': 7,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 900.0,
  'BinHigh': inf},
 {'StateID': 104,
  'TemporalPropertyID': 7,
  'MethodName': 'equal_width',
  'BinId': 3,
  'BinLow': 600.0,
  'BinHigh': 900.0},
 {'StateID': 105,
  'TemporalPropertyID': 6,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 25.556,
  'BinHigh': inf},
 {'StateID': 106,
  'TemporalPropertyID': 6,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': -3.333},
 {'StateID': 107,
  'TemporalPropertyID': 6,
  'MethodName': 'equal_width',
  'BinId': 2,
  'BinLow': -3.333,
  'BinHigh': 11.111},
 {'StateID': 108,
  'TemporalPropertyID': 50804,
  'MethodName': 'equal_width',
  'BinId': 2,
  'BinLow': 16.75,
  'BinHigh': 28.5},
 {'StateID': 109,
  'TemporalPropertyID': 50804,
  'MethodName': 'equal_width',
  'BinId': 3,
  'BinLow': 28.5,
  'BinHigh': 40.25},
 {'StateID': 110,
  'TemporalPropertyID': 50804,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': 16.75},
 {'StateID': 111,
  'TemporalPropertyID': 50804,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 40.25,
  'BinHigh': inf},
 {'StateID': 112,
  'TemporalPropertyID': 50811,
  'MethodName': 'equal_width',
  'BinId': 3,
  'BinLow': 10.05,
  'BinHigh': 12.575},
 {'StateID': 113,
  'TemporalPropertyID': 50811,
  'MethodName': 'equal_width',
  'BinId': 2,
  'BinLow': 7.525,
  'BinHigh': 10.05},
 {'StateID': 114,
  'TemporalPropertyID': 50811,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': 7.525},
 {'StateID': 115,
  'TemporalPropertyID': 50811,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 12.575,
  'BinHigh': inf},
 {'StateID': 116,
  'TemporalPropertyID': 50811,
  'MethodName': 'gradient',
  'BinId': 2,
  'BinLow': -30,
  'BinHigh': 30},
 {'StateID': 117,
  'TemporalPropertyID': 50822,
  'MethodName': 'equal_width',
  'BinId': 3,
  'BinLow': 4.6,
  'BinHigh': 5.5},
 {'StateID': 118,
  'TemporalPropertyID': 50822,
  'MethodName': 'equal_width',
  'BinId': 2,
  'BinLow': 3.7,
  'BinHigh': 4.6},
 {'StateID': 119,
  'TemporalPropertyID': 50822,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 5.5,
  'BinHigh': inf},
 {'StateID': 120,
  'TemporalPropertyID': 50822,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': 3.7},
 {'StateID': 121,
  'TemporalPropertyID': 50882,
  'MethodName': 'equal_width',
  'BinId': 2,
  'BinLow': 19.5,
  'BinHigh': 31.0},
 {'StateID': 122,
  'TemporalPropertyID': 50882,
  'MethodName': 'equal_width',
  'BinId': 1,
  'BinLow': -inf,
  'BinHigh': 19.5},
 {'StateID': 123,
  'TemporalPropertyID': 50882,
  'MethodName': 'equal_width',
  'BinId': 3,
  'BinLow': 31.0,
  'BinHigh': 42.5},
 {'StateID': 124,
  'TemporalPropertyID': 50882,
  'MethodName': 'equal_width',
  'BinId': 4,
  'BinLow': 42.5,
  'BinHigh': inf},
 {'StateID': 125,
  'TemporalPropertyID': 50902,
  'MethodName': 'equal_width',
  'BinId': 3,
  'BinLow': 104.0,
  'BinHigh': 116.5},
 {'StateID': 126,